### PR TITLE
Prep retcode syntax for Julia v1.9

### PR DESCRIPTION
**Pull request by henrikjaerleblad**
I think I prepared it for the change in SciML retcode syntax.

The warning will pop out automatically when using solve(), until Julia v1.9

### CODE REVIEW

**Comment by henrikjaerleblad** [comment]
The :TotalFailure is fine for now. Prep it if you want as well.

Success and Terminated are now both classified as Successful according to SciML. Hence the shortening of the boolean checks

**Comment by lstagner** [comment]
Looks good

**Comment by henrikjaerleblad** [comment]
Changed :TotalFailure to Retcode.Failure.

I think henrikbranch is ready for merging with masterbranch now. It works to integrate orbits.
For some reason, the warning is still printed when using solve() but I think it's because OrdinaryDiffEq has yet to update everything internally.

**Comment by henrikjaerleblad** [comment]
Can we merge this w master now @lstagner ?

**Pull request merged**
